# Generated by Django 4.2 on 2025-03-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(limit_choices_to={'rol': 'residente'}, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_comunes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Común',
                'verbose_name_plural': 'Gastos Comunes',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
