# Generated by Django 4.2 on 2025-03-24 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multa_creada', 'Multa Creada'), ('multa_pagada', 'Multa Pagada'), ('multa_anulada', 'Multa Anulada'), ('gasto_creado', 'Gasto Común Creado'), ('gasto_pagado', 'Gasto Común Pagado'), ('gasto_vencido', 'Gasto Común Vencido'), ('usuario_creado', 'Usuario Creado'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
